instrumentation:
  extensions:
    - .ts
  excludes:
    - 'src/main.*'
    - 'spec/**'
    - '*.d.ts'
    - '*.spec.ts'
  include-all-sources: true

check:
  global:
    statements: 90
    lines: 90
  each:
    statements: 90
    lines: 90
