language: node_js

node_js:
  - '6'

install:
  - npm install
  - npm install -g codecov

script:
  - npm run build
  - codecov

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/
